#include <chrono>
#include <cmath>
#include <gecko/core/boot.h>
#include <gecko/core/scope.h>
#include <gecko/core/services.h>
#include <gecko/core/services/events.h>
#include <gecko/core/services/jobs.h>
#include <gecko/core/services/log.h>
#include <gecko/core/services/modules.h>
#include <gecko/core/version.h>
#include <gecko/graphics/graphics_device.h>
#include <gecko/platform/platform_context.h>
#include <gecko/platform/platform_module.h>
#include <gecko/runtime/console_log_sink.h>
#include <gecko/runtime/event_bus.h>
#include <gecko/runtime/file_log_sink.h>
#include <gecko/runtime/immediate_logger.h>
#include <gecko/runtime/module_registry.h>
#include <gecko/runtime/ring_profiler.h>
#include <gecko/runtime/runtime_module.h>
#include <gecko/runtime/thread_pool_job_system.h>
#include <gecko/runtime/tracking_allocator.h>

// Shader SPIR-V blobs, generated by CMake from the HLSL sources under
// examples/graphics_example/shaders/ at build time.
#include "shaders.h"

using namespace gecko;
using namespace gecko::platform;
using namespace gecko::graphics;

namespace app::graphics_example::labels {
inline constexpr ::gecko::Label App =
    ::gecko::MakeLabel("app.graphics_example");
inline constexpr ::gecko::Label Main =
    ::gecko::MakeLabel("app.graphics_example.main");
}  // namespace app::graphics_example::labels

namespace {

class AppModule final : public ::gecko::IModule
{
public:
  [[nodiscard]] ::gecko::Label RootLabel() const noexcept override
  {
    return app::graphics_example::labels::App;
  }

  [[nodiscard]] bool Startup(
      ::gecko::IModuleRegistry& /*modules*/) noexcept override
  {
    return true;
  }

  void Shutdown(::gecko::IModuleRegistry& /*modules*/) noexcept override
  {}
};

AppModule g_AppModule;

struct Vertex
{
  float Position[3];
  float Color[3];
};

constexpr Vertex TriangleVertices[] = {
    {{0.0F, 0.5F, 0.0F}, {1.0F, 0.0F, 0.0F}},    // top    — red
    {{0.5F, -0.5F, 0.0F}, {0.0F, 1.0F, 0.0F}},   // right  — green
    {{-0.5F, -0.5F, 0.0F}, {0.0F, 0.0F, 1.0F}},  // left   — blue
};

// Per-window state.
struct WindowSlot
{
  WindowHandle Handle {};
  Swapchain SC {};
  bool ResizeDirty {false};
  u32 ResizeW {0};
  u32 ResizeH {0};
};

}  // namespace

int main()
{
  runtime::TrackingAllocator trackingAlloc;
  runtime::RingProfiler ringProfiler(1 << 16);
  runtime::ImmediateLogger ringLogger;
  ringLogger.SetThreadSafe(true);
  runtime::ModuleRegistry moduleRegistry;
  runtime::EventBus eventBus;
  runtime::ThreadPoolJobSystem jobSystem;
  jobSystem.SetWorkerThreadCount(4);

  GECKO_BOOT((Services {.Allocator = &trackingAlloc,
                        .JobSystem = &jobSystem,
                        .Profiler = &ringProfiler,
                        .Logger = &ringLogger,
                        .Modules = &moduleRegistry,
                        .EventBus = &eventBus}));

  runtime::ConsoleLogSink consoleSink;
  runtime::FileLogSink fileSink("log.txt");
  if (auto* logger = GetLogger())
  {
    fileSink.RegisterWith(logger);
    consoleSink.RegisterWith(logger);
    logger->SetLevel(LogLevel::Info);
  }

  {
    GECKO_FUNC(app::graphics_example::labels::Main);
    GECKO_INFO(app::graphics_example::labels::Main, gecko::VersionFullString());

    (void)InstallModule(runtime::GetModule());
    (void)InstallModule(platform::GetModule());
    (void)InstallModule(g_AppModule);

    PlatformContext ctx(PlatformConfig {});

    // ── Two windows ───────────────────────────────────────────────
    WindowSlot slots[2];
    const char* titles[2] = {
        "Gecko Graphics — Window A",
        "Gecko Graphics — Window B",
    };
    for (u32 i = 0; i < 2; ++i)
    {
      WindowDesc wd;
      wd.Title = titles[i];
      wd.Size = {1280, 720};
      wd.Visible = true;
      wd.Resizable = true;
      wd.Mode = WindowMode::Windowed;

      slots[i].Handle = ctx.Windows().CreateWindow(wd);
      if (!slots[i].Handle.IsValid())
      {
        GECKO_ERROR(app::graphics_example::labels::Main,
                    "Failed to create window %u", i);
        return 1;
      }
    }
    GECKO_INFO(app::graphics_example::labels::Main, "Two windows created");

    // ── Graphics device ──────────────────────────────────────────
    auto device = CreateGraphicsDevice(
        GraphicsDeviceDesc {.Backend = GraphicsBackend::Vulkan,
                            .Debug = true,
                            .AppName = "graphics_example"});
    GECKO_INFO(app::graphics_example::labels::Main, "Graphics device created");

    // ── Swapchains ───────────────────────────────────────────────
    for (u32 i = 0; i < 2; ++i)
    {
      NativeWindowHandle native =
          ctx.Windows().GetNativeWindowHandle(slots[i].Handle);
      Extent2D sz = ctx.Windows().GetClientSize(slots[i].Handle);

      SwapchainDesc scDesc;
      scDesc.Width = sz.Width;
      scDesc.Height = sz.Height;
      scDesc.NumBackBuffers = 2;
      scDesc.Format = DataFormat::R8G8B8A8_UNORM;
      scDesc.VSync = true;

      slots[i].SC = device->CreateSwapchain(native, scDesc);
      if (!slots[i].SC.IsValid())
      {
        GECKO_WARN(app::graphics_example::labels::Main,
                   "Swapchain %u not created (NullDevice?)", i);
      }
    }

    // ── Offscreen render target ───────────────────────────────────
    constexpr u32 kOffscreenW = 1280;
    constexpr u32 kOffscreenH = 720;
    constexpr auto kOffscreenFmt = DataFormat::R8G8B8A8_UNORM;

    RenderTargetDesc rtDesc;
    rtDesc.Width = kOffscreenW;
    rtDesc.Height = kOffscreenH;
    rtDesc.NumRenderTargets = 1;
    rtDesc.RenderTargetFormats[0] = kOffscreenFmt;
    rtDesc.RenderTargetClearValues[0] =
        ClearValue::RenderTarget(0.1F, 0.1F, 0.15F, 1.0F);

    RenderTarget offscreenRT = device->CreateRenderTarget(rtDesc);
    if (offscreenRT.IsValid())
      GECKO_INFO(app::graphics_example::labels::Main,
                 "Offscreen render target created (%ux%u)", kOffscreenW,
                 kOffscreenH);
    else
      GECKO_WARN(app::graphics_example::labels::Main,
                 "Offscreen render target creation failed");

    // ── Storage textures written by the plasma compute shader ────
    // Two separate outputs so two job-system workers can dispatch compute
    // in parallel without aliasing. HLSL's `RWTexture2D<float4>` compiles
    // to SPIR-V with an Rgba32f format operand (glslc's HLSL front-end
    // ignores [[vk::image_format]]) — match that here.
    TextureDesc plasmaDesc {};
    plasmaDesc.Width = kOffscreenW;
    plasmaDesc.Height = kOffscreenH;
    plasmaDesc.Format = DataFormat::R32G32B32A32_FLOAT;
    plasmaDesc.Type = TextureType::Tex2D;
    plasmaDesc.Memory = MemoryType::Dedicated;
    plasmaDesc.AllowUnorderedAccess = true;

    Texture plasmaTex[2] {};
    for (u32 i = 0; i < 2; ++i)
    {
      plasmaDesc.DebugName =
          (i == 0) ? "PlasmaStorageTexture[0]" : "PlasmaStorageTexture[1]";
      plasmaTex[i] = device->CreateTexture(plasmaDesc);
    }
    if (plasmaTex[0].IsValid() && plasmaTex[1].IsValid())
      GECKO_INFO(app::graphics_example::labels::Main,
                 "Plasma storage textures created (2x %ux%u)", kOffscreenW,
                 kOffscreenH);
    else
      GECKO_WARN(app::graphics_example::labels::Main,
                 "Plasma storage texture creation failed");

    // ── Vertex buffer for triangle ───────────────────────────────
    VertexBufferDesc vbDesc;
    vbDesc.NumVertices = 3;
    vbDesc.VertexSize = sizeof(Vertex);
    vbDesc.Memory = MemoryType::Dedicated;

    Buffer vertexBuffer = device->CreateVertexBuffer(vbDesc);
    if (vertexBuffer.IsValid())
    {
      const auto* raw = reinterpret_cast<const gecko::byte*>(TriangleVertices);
      const usize size = sizeof(TriangleVertices);
      device->UploadBufferData(vertexBuffer, {raw, size});
    }

    // ── Shader binaries (generated by CMake from HLSL sources) ──
    namespace shaders = ::gecko::graphics_example::shaders;

    // ── Pipeline 1: triangle -> offscreen RT ─────────────────────
    VertexLayout triLayout;
    triLayout.AddAttribute(DataFormat::R32G32B32_FLOAT, "a_Position");
    triLayout.AddAttribute(DataFormat::R32G32B32_FLOAT, "a_Color");

    GraphicsPipelineDesc triPDesc;
    triPDesc.VertexShader = ShaderCode {
        .Format = ShaderFormat::SPIRV,
        .Bytes = {reinterpret_cast<const gecko::byte*>(shaders::TriangleVert),
                  sizeof(shaders::TriangleVert)},
    };
    triPDesc.PixelShader = ShaderCode {
        .Format = ShaderFormat::SPIRV,
        .Bytes = {reinterpret_cast<const gecko::byte*>(shaders::TriangleFrag),
                  sizeof(shaders::TriangleFrag)},
    };
    triPDesc.Layout = triLayout;
    triPDesc.NumRenderTargets = 1;
    triPDesc.RenderTargetFormats[0] = kOffscreenFmt;
    triPDesc.Culling = CullMode::None;
    triPDesc.PushConstantBytes = 16;  // float Time + 3 pad
    triPDesc.DebugName = "TrianglePipeline";

    GraphicsPipeline trianglePipeline =
        device->CreateGraphicsPipeline(triPDesc);

    // ── Pipeline 2: fullscreen blit -> swapchain ─────────────────
    // Same pipeline used against both swapchains (their backbuffers use the
    // same format).  Binding 0: SRV sampled image. Binding 1: sampler.
    GraphicsPipelineDesc blitPDesc;
    blitPDesc.VertexShader = ShaderCode {
        .Format = ShaderFormat::SPIRV,
        .Bytes = {reinterpret_cast<const gecko::byte*>(shaders::FullscreenVert),
                  sizeof(shaders::FullscreenVert)},
    };
    blitPDesc.PixelShader = ShaderCode {
        .Format = ShaderFormat::SPIRV,
        .Bytes = {reinterpret_cast<const gecko::byte*>(shaders::FullscreenFrag),
                  sizeof(shaders::FullscreenFrag)},
    };
    blitPDesc.Layout = {};  // no vertex input
    blitPDesc.NumRenderTargets = 1;
    blitPDesc.RenderTargetFormats[0] = slots[0].SC.IsValid()
                                           ? slots[0].SC.Desc.Format
                                           : DataFormat::R8G8B8A8_UNORM;
    blitPDesc.Culling = CullMode::None;

    blitPDesc.PipelineResources[0] =
        PipelineResource::TextureBinding(1, ShaderType::Pixel);
    blitPDesc.PipelineResources[1] =
        PipelineResource::SamplerBinding(1, ShaderType::Pixel);
    blitPDesc.NumPipelineResources = 2;
    blitPDesc.PushConstantBytes = 16;  // float4 Tint
    blitPDesc.DebugName = "BlitPipeline";

    GraphicsPipeline blitPipeline = device->CreateGraphicsPipeline(blitPDesc);

    // ── Pipeline 3: plasma compute -> plasmaTex ──────────────────
    ComputePipelineDesc plasmaPDesc;
    plasmaPDesc.ComputeShader = ShaderCode {
        .Format = ShaderFormat::SPIRV,
        .Bytes = {reinterpret_cast<const gecko::byte*>(shaders::PlasmaComp),
                  sizeof(shaders::PlasmaComp)},
    };
    plasmaPDesc.PipelineResources[0] =
        PipelineResource::RWTextureBinding(1, ShaderType::Compute);
    plasmaPDesc.NumPipelineResources = 1;
    plasmaPDesc.PushConstantBytes = 16;  // float Time + 3 pad
    plasmaPDesc.DebugName = "PlasmaComputePipeline";

    ComputePipeline plasmaPipeline = device->CreateComputePipeline(plasmaPDesc);
    if (plasmaPipeline.IsValid())
      GECKO_INFO(app::graphics_example::labels::Main,
                 "Compute pipeline ready (plasma)");
    else
      GECKO_WARN(app::graphics_example::labels::Main,
                 "Plasma compute pipeline creation failed");

    SamplerDesc blitSamplerDesc {};
    blitSamplerDesc.Filter = SamplerFilter::Linear;
    blitSamplerDesc.WrapMode = SamplerWrapMode::Clamp;
    blitSamplerDesc.DebugName = "BlitSampler";
    Sampler blitSampler = device->CreateSampler(blitSamplerDesc);

    // ── Indirect draw args buffer (VkDrawIndirectCommand layout) ─
    // {vertexCount=3, instanceCount=1, firstVertex=0, firstInstance=0}
    StructuredBufferDesc indirectDesc {};
    indirectDesc.NumElements = 1;
    indirectDesc.ElementSize = 16;  // 4 × u32
    indirectDesc.Memory = MemoryType::Dedicated;
    indirectDesc.DebugName = "TriangleIndirectArgs";
    Buffer indirectBuffer = device->CreateStructuredBuffer(indirectDesc);
    if (indirectBuffer.IsValid())
    {
      const u32 indirectArgs[4] = {3, 1, 0, 0};
      device->UploadBufferData(
          indirectBuffer, {reinterpret_cast<const gecko::byte*>(indirectArgs),
                           sizeof(indirectArgs)});
    }

    // ── Timestamp query pool (4 slots: pass1-begin/end, blit-begin/end) ──
    QueryPoolDesc qpDesc {};
    qpDesc.Count = 4;
    qpDesc.DebugName = "FrameTimestamps";
    QueryPool timestampPool = device->CreateTimestampQueryPool(qpDesc);

    if (!trianglePipeline.IsValid() || !blitPipeline.IsValid())
    {
      GECKO_WARN(app::graphics_example::labels::Main,
                 "One or more pipelines failed to build — rendering disabled");
    }
    else
    {
      GECKO_INFO(app::graphics_example::labels::Main,
                 "Pipelines ready (triangle + fullscreen blit)");
    }

    // ── Event subscriptions ───────────────────────────────────────
    bool running = true;

    auto closeSub = SubscribeEvent(
        events::WindowCloseRequested,
        [](void* user, const EventMeta&, EventView view) {
          (void)view;
          *static_cast<bool*>(user) = false;
        },
        &running);

    struct ResizeContext
    {
      PlatformContext* Ctx {nullptr};
      WindowSlot* Slots {nullptr};
    };
    ResizeContext rctx {&ctx, slots};

    auto resizeSub = SubscribeEvent(
        events::WindowResized,
        [](void* user, const EventMeta&, EventView view) {
          const auto* payload =
              reinterpret_cast<const events::WindowResizedPayload*>(
                  view.Data());
          auto* rc = static_cast<ResizeContext*>(user);
          for (u32 i = 0; i < 2; ++i)
          {
            if (rc->Slots[i].Handle == payload->Window)
            {
              rc->Slots[i].ResizeW = payload->Width;
              rc->Slots[i].ResizeH = payload->Height;
              rc->Slots[i].ResizeDirty = true;
            }
          }
        },
        &rctx);

    auto keySub = SubscribeEvent(
        events::WindowKey,
        [](void* user, const EventMeta&, EventView view) {
          const auto* payload =
              reinterpret_cast<const events::WindowKeyPayload*>(view.Data());
          if (payload->Down && !payload->Repeat &&
              payload->Key == KeyCode::Escape)
          {
            *static_cast<bool*>(user) = false;
          }
        },
        &running);

    GECKO_INFO(app::graphics_example::labels::Main,
               "Entering frame loop — Escape or close to quit");

    const auto startTime = ::std::chrono::steady_clock::now();
    u64 frameIndex = 0;

    auto renderFrame = [&]() {
      // Coalesce pending resizes into a single swapchain rebuild per window.
      for (u32 i = 0; i < 2; ++i)
      {
        if (slots[i].ResizeDirty)
        {
          if (slots[i].ResizeW > 0 && slots[i].ResizeH > 0)
          {
            slots[i].SC.Desc.Width = slots[i].ResizeW;
            slots[i].SC.Desc.Height = slots[i].ResizeH;
          }
          device->ResizeSwapchain(slots[i].SC);
          slots[i].ResizeDirty = false;
        }
      }

      if (!trianglePipeline.IsValid() || !blitPipeline.IsValid() ||
          !vertexBuffer.IsValid() || !offscreenRT.IsValid())
        return;

      // Acquire both swapchains (skip any that fail).
      FrameContext frames[2] {};
      for (u32 i = 0; i < 2; ++i)
      {
        if (slots[i].SC.IsValid())
          frames[i] = device->BeginFrame(slots[i].SC);
      }
      if (!frames[0].Valid && !frames[1].Valid)
        return;

      auto cmd = device->CreateGraphicsCommandList();
      cmd->Begin();

      const bool haveTimestamps = timestampPool.IsValid();
      if (haveTimestamps)
        cmd->ResetTimestamps(timestampPool, 0, 4);

      const f32 time = ::std::chrono::duration<f32>(
                           ::std::chrono::steady_clock::now() - startTime)
                           .count();

      // ── Parallel compute ─────────────────────────────────────────
      // Record two plasma dispatches on separate job-system workers, each
      // writing into its own storage texture. This exercises the engine's
      // per-thread Vulkan command pools + queue-submit mutex. We only
      // record in parallel; submission itself is serialised on the main
      // thread so the blit pass below can assume both compute textures are
      // already in SHADER_READ_ONLY when it runs.
      const bool haveCompute =
          plasmaPipeline.IsValid() && plasmaTex[0].IsValid() &&
          plasmaTex[1].IsValid();

      Unique<ICommandList> computeCmd[2];
      JobHandle computeJobs[2] {};

      if (haveCompute)
      {
        for (u32 i = 0; i < 2; ++i)
        {
          const f32 tOffset = (i == 0) ? 0.0F : 3.14159F;
          computeJobs[i] = SubmitJob([&, i, time, tOffset]() {
            computeCmd[i] = device->CreateComputeCommandList();
            if (!computeCmd[i])
              return;
            computeCmd[i]->Begin();
            computeCmd[i]->BindPipeline(plasmaPipeline);
            computeCmd[i]->BindRWTexture(0, plasmaTex[i]);
            f32 pc[4] = {time + tOffset, 0.0F, 0.0F, 0.0F};
            computeCmd[i]->SetConstants(
                0, {reinterpret_cast<const gecko::byte*>(pc), sizeof(pc)});
            const u32 gx = (kOffscreenW + 15) / 16;
            const u32 gy = (kOffscreenH + 15) / 16;
            computeCmd[i]->Dispatch(gx, gy, 1);
            computeCmd[i]->TransitionTextureForRead(plasmaTex[i]);
            computeCmd[i]->End();
          });
        }
        WaitForJobs(computeJobs, 2);
        // Submit from the main thread, in deterministic order.
        for (u32 i = 0; i < 2; ++i)
          if (computeCmd[i])
            device->ExecuteComputeCommandList(::std::move(computeCmd[i]));
      }

      // Pass 1: render the spinning-coloured triangle into the offscreen RT
      // using an indirect draw + time push constant.
      ClearValue rtClear = ClearValue::RenderTarget(0.08F, 0.08F, 0.12F, 1.0F);
      cmd->BeginRendering(offscreenRT, &rtClear);
      cmd->SetViewport(0.0F, 0.0F, static_cast<f32>(kOffscreenW),
                       static_cast<f32>(kOffscreenH));
      cmd->SetScissor(0, 0, kOffscreenW, kOffscreenH);
      cmd->BindPipeline(trianglePipeline);
      cmd->BindVertexBuffer(vertexBuffer);
      {
        f32 pc[4] = {time, 0.0F, 0.0F, 0.0F};
        cmd->SetConstants(
            0, {reinterpret_cast<const gecko::byte*>(pc), sizeof(pc)});
      }
      if (haveTimestamps)
        cmd->WriteTimestamp(timestampPool, 0);
      if (indirectBuffer.IsValid())
        cmd->DrawIndirect(indirectBuffer, 0, 1, 16);
      else
        cmd->Draw(3);
      if (haveTimestamps)
        cmd->WriteTimestamp(timestampPool, 1);
      cmd->EndRendering();
      // After EndRendering the offscreen target is in SHADER_READ_ONLY.

      // Pass 2 & 3: fullscreen-quad blit into each swapchain. Window A
      // samples the triangle offscreen RT; Window B samples the plasma
      // compute output. One command list, one submit, one Present.
      const Texture& triSampled = offscreenRT.RenderTextures[0];
      const bool havePlasma =
          plasmaPipeline.IsValid() && plasmaTex[0].IsValid() &&
          plasmaTex[1].IsValid();

      // Tint pulses between 0.6 and 1.0 over time so push constants are
      // visibly affecting output.
      const f32 pulse = 0.8F + 0.2F * ::std::sin(time * 2.0F);
      const f32 tintArr[4] = {pulse, pulse, pulse, 1.0F};

      if (haveTimestamps)
        cmd->WriteTimestamp(timestampPool, 2);
      for (u32 i = 0; i < 2; ++i)
      {
        if (!frames[i].Valid)
          continue;
        const Texture& src =
            (i == 1 && havePlasma) ? plasmaTex[1]
          : (i == 0 && havePlasma) ? plasmaTex[0]
          : triSampled;
        ClearValue scClear = ClearValue::RenderTarget(0.0F, 0.0F, 0.0F, 1.0F);
        cmd->BeginRendering(frames[i].BackBuffer, &scClear);
        cmd->SetViewport(0.0F, 0.0F,
                         static_cast<f32>(frames[i].BackBuffer.Desc.Width),
                         static_cast<f32>(frames[i].BackBuffer.Desc.Height));
        cmd->SetScissor(0, 0, frames[i].BackBuffer.Desc.Width,
                        frames[i].BackBuffer.Desc.Height);
        cmd->BindPipeline(blitPipeline);
        cmd->BindTexture(0, src);
        cmd->BindSampler(1, blitSampler);
        cmd->SetConstants(0, {reinterpret_cast<const gecko::byte*>(tintArr),
                              sizeof(tintArr)});
        cmd->Draw(3);
        cmd->EndRendering();
      }
      if (haveTimestamps)
        cmd->WriteTimestamp(timestampPool, 3);

      cmd->End();
      device->ExecuteGraphicsCommandList(::std::move(cmd));

      // Present both swapchains in one driver call.
      FrameContext toPresent[2] {};
      u32 presentCount = 0;
      for (u32 i = 0; i < 2; ++i)
      {
        if (frames[i].Valid)
          toPresent[presentCount++] = ::std::move(frames[i]);
      }
      device->Present(
          ::std::span<const FrameContext> {toPresent, presentCount});

      // Log GPU timings once per ~60 frames (WAIT-blocks until ready).
      if (haveTimestamps && (frameIndex % 60) == 0 && frameIndex > 0)
      {
        u64 ns[4] {};
        u32 got = device->ReadTimestamps(timestampPool, 0, ns);
        if (got == 4)
        {
          const f64 triMs = static_cast<f64>(ns[1] - ns[0]) / 1.0e6;
          const f64 blitMs = static_cast<f64>(ns[3] - ns[2]) / 1.0e6;
          GECKO_INFO(app::graphics_example::labels::Main,
                     "GPU: triangle pass = %.3f ms, blit pass = %.3f ms", triMs,
                     blitMs);
        }
      }
      ++frameIndex;
    };

    ctx.SetModalFrameCallback(
        [](void* ud) { (*static_cast<decltype(&renderFrame)>(ud))(); },
        &renderFrame);

    while (running)
    {
      ctx.PumpEvents();
      (void)DispatchEvents();
      renderFrame();
    }

    ctx.SetModalFrameCallback(nullptr, nullptr);

    // Destroy in reverse order.
    for (u32 i = 0; i < 2; ++i)
    {
      device->DestroySwapchain(slots[i].SC);
      ctx.Windows().DestroyWindow(slots[i].Handle);
    }

    GECKO_INFO(app::graphics_example::labels::Main, "Shutdown complete");
  }

  GECKO_SHUTDOWN();
  ::std::printf("Graphics example finished.\n");
  return 0;
}
