#include <chrono>
#include <cmath>
#include <cstdlib>
#include <gecko/core/engine.h>
#include <gecko/core/scope.h>
#include <gecko/core/services.h>
#include <gecko/core/services/events.h>
#include <gecko/core/services/jobs.h>
#include <gecko/core/services/log.h>
#include <gecko/core/services/modules.h>
#include <gecko/core/version.h>
#include <gecko/graphics/gpu_profiler.h>
#include <gecko/graphics/graphics_device.h>
#include <gecko/platform/platform_module.h>
#include <gecko/runtime/async_trace_profiler_sink.h>
#include <gecko/runtime/console_log_sink.h>
#include <gecko/runtime/event_bus.h>
#include <gecko/runtime/file_log_sink.h>
#include <gecko/runtime/immediate_logger.h>
#include <gecko/runtime/ring_profiler.h>
#include <gecko/runtime/runtime_module.h>
#include <gecko/runtime/thread_pool_job_system.h>
#include <gecko/runtime/tracking_allocator.h>

// Shader SPIR-V blobs, generated by CMake from the HLSL sources under
// examples/graphics_example/shaders/ at build time.
#include "shaders.h"

using namespace gecko;
using namespace gecko::platform;
using namespace gecko::graphics;

namespace app::graphics_example::labels {
inline constexpr ::gecko::Label App =
    ::gecko::MakeLabel("app.graphics_example");
inline constexpr ::gecko::Label Main =
    ::gecko::MakeLabel("app.graphics_example.main");
}  // namespace app::graphics_example::labels

namespace {

class AppModule final : public ::gecko::IModule
{
public:
  [[nodiscard]] ::gecko::Label RootLabel() const noexcept override
  {
    return app::graphics_example::labels::App;
  }

  [[nodiscard]] bool Startup(
      ::gecko::IModuleRegistry& /*modules*/) noexcept override
  {
    return true;
  }

  void Shutdown(::gecko::IModuleRegistry& /*modules*/) noexcept override
  {}
};

AppModule g_AppModule;

struct Vertex
{
  float Position[3];
  float Color[3];
};

constexpr Vertex TriangleVertices[] = {
    {{0.0F, 0.5F, 0.0F}, {1.0F, 0.0F, 0.0F}},    // top    — red
    {{0.5F, -0.5F, 0.0F}, {0.0F, 1.0F, 0.0F}},   // right  — green
    {{-0.5F, -0.5F, 0.0F}, {0.0F, 0.0F, 1.0F}},  // left   — blue
};

// Per-window state.
struct WindowSlot
{
  WindowHandle Handle {};
  Swapchain SC {};
  bool ResizeDirty {false};
  u32 ResizeW {0};
  u32 ResizeH {0};
};

}  // namespace

int main()
{
  runtime::TrackingAllocator trackingAlloc;
  if (!SetAllocator(&trackingAlloc))
    return 1;

  // 1<<20 slots: with profiler at Detailed level the graphics example can
  // emit ~30k events/sec; a 64k ring overflows in ~2s, dropping subsequent
  // events (including the AppRun ZoneEnd, showing as '[incomplete]' in
  // Perfetto). 1M is plenty.
  runtime::RingProfiler ringProfiler(1 << 20);
  runtime::ImmediateLogger ringLogger;
  ringLogger.SetThreadSafe(true);
  runtime::EventBus eventBus;
  runtime::ThreadPoolJobSystem jobSystem;
  jobSystem.SetWorkerThreadCount(4);

  runtime::CoreServicesModule runtimeModule(jobSystem, ringProfiler, ringLogger,
                                            eventBus);
  platform::PlatformModule platformModule;

  auto engine = Engine::Create({&runtimeModule, &platformModule, &g_AppModule});
  if (!engine)
  {
    ResetAllocator();
    return 1;
  }

#if defined(GECKO_DEBUG) || defined(_DEBUG) || !defined(NDEBUG)
  // Debug: full picture, every Vulkan op + blind-spot zone visible.
  ::gecko::GetProfiler()->SetMinLevel(::gecko::ProfLevel::Detailed);
#else
  // Release: keep only the high-level picture (Always = frame, GPU passes,
  // Present, ExecuteGraphicsCommandList) plus Normal scopes. Detailed
  // per-vk-op scopes are dropped from the trace sink.
  ::gecko::GetProfiler()->SetMinLevel(::gecko::ProfLevel::Normal);
#endif

  // Watch the scopes whose rolling-average we'll display in the HUD.
  // (Other scopes still get Last/Min/Max/Count for free; only Avg is
  // opt-in because each watched scope owns a small ring buffer.)
  if (auto* prof = ::gecko::GetProfiler())
  {
    prof->WatchScope("frame", 240);
    prof->WatchScope("renderFrame", 240);
    prof->WatchScope("TrianglePass", 240, ::gecko::ProfSource::GPU);
    prof->WatchScope("BlitPass", 240, ::gecko::ProfSource::GPU);
    prof->WatchScope("PlasmaCompute", 240);
    // Reset stats every 500 ms so HUD numbers track recent behaviour.
    prof->SetStatsResetIntervalMs(500);
  }

  // Register a category for the demo "terrain" compute job so it can be
  // toggled independently of the rest of the renderer (F4 dumps stats by
  // category).
  u8 catTerrain = 0;
  if (auto* prof = ::gecko::GetProfiler())
    catTerrain = prof->RegisterCategory("terrain");

  runtime::ConsoleLogSink consoleSink;
  runtime::FileLogSink fileSink("log.txt");

  if (auto* logger = GetLogger())
  {
    fileSink.RegisterWith(logger);
    consoleSink.RegisterWith(logger);
    logger->SetLevel(LogLevel::Info);
  }

  runtime::AsyncTraceProfilerSink traceSink("gecko_trace.json");

  // Name the main thread so trace viewers show "main" instead of a raw TID.
  ::gecko::SetThreadProfilerName("main");

  GECKO_PUSH_LABEL(app::graphics_example::labels::Main);
  GECKO_INFO(app::graphics_example::labels::Main, gecko::VersionFullString());

  if (!traceSink.IsOpen())
  {
    GECKO_WARN(app::graphics_example::labels::Main,
               "Failed to open trace profiler sink\n");
  }
  else
  {
    if (auto* profiler = GetProfiler())
    {
      traceSink.RegisterWith(profiler);
      profiler->SetTraceEnabled(true);
      // Default the trace sink's level to match the profiler's min level —
      // i.e. Detailed in debug builds (everything in the JSON), Normal in
      // release. The trace sink filter is a *cap* on what reaches the file;
      // it never lifts events the profiler itself has filtered out.
      // Override with GECKO_TRACE_LEVEL=always|normal|detailed.
      ::gecko::ProfLevel traceLevel = profiler->GetMinLevel();
      if (const char* env = ::std::getenv("GECKO_TRACE_LEVEL"))
      {
        if (env[0] == 'a' || env[0] == 'A')
          traceLevel = ::gecko::ProfLevel::Always;
        else if (env[0] == 'd' || env[0] == 'D')
          traceLevel = ::gecko::ProfLevel::Detailed;
        else
          traceLevel = ::gecko::ProfLevel::Normal;
      }
      traceSink.SetMinLevel(traceLevel);
    }
  }

  {
    GECKO_SCOPE_ALWAYS_NAMED(app::graphics_example::labels::Main, "AppRun");

    // ── Two windows ───────────────────────────────────────────────
    WindowSlot slots[2];
    const char* titles[2] = {
        "Gecko Graphics - Window A",
        "Gecko Graphics - Window B",
    };
    for (u32 i = 0; i < 2; ++i)
    {
      WindowDesc wd;
      wd.Title = titles[i];
      wd.Size = {1280, 720};
      wd.Visible = true;
      wd.Resizable = true;
      wd.Mode = WindowMode::Windowed;

      slots[i].Handle = ::gecko::platform::GetWindows()->CreateWindow(wd);
      if (!slots[i].Handle.IsValid())
      {
        GECKO_ERROR(app::graphics_example::labels::Main,
                    "Failed to create window %u", i);
        return 1;
      }
    }
    GECKO_INFO(app::graphics_example::labels::Main, "Two windows created");

    // ── Graphics device ──────────────────────────────────────────
    // Vulkan validation layers add 5-30s to startup under gdb. Off by
    // default; opt in with GECKO_VK_VALIDATION=1.
    const bool wantValidation = []() {
      const char* v = ::std::getenv("GECKO_VK_VALIDATION");
      return v && v[0] != '\0' && v[0] != '0';
    }();
    auto device = CreateGraphicsDevice(
        GraphicsDeviceDesc {.Backend = GraphicsBackend::Vulkan,
                            .Debug = wantValidation,
                            .AppName = "graphics_example"});
    GECKO_INFO(app::graphics_example::labels::Main, "Graphics device created");

    // ── Swapchains ───────────────────────────────────────────────
    for (u32 i = 0; i < 2; ++i)
    {
      NativeWindowHandle native =
          ::gecko::platform::GetWindows()->GetNativeWindowHandle(
              slots[i].Handle);
      Extent2D sz =
          ::gecko::platform::GetWindows()->GetClientSize(slots[i].Handle);

      SwapchainDesc scDesc;
      scDesc.Width = sz.Width;
      scDesc.Height = sz.Height;
      scDesc.NumBackBuffers = 2;
      scDesc.Format = DataFormat::R8G8B8A8_UNORM;
      scDesc.VSync = false;

      slots[i].SC = device->CreateSwapchain(native, scDesc);
      if (!slots[i].SC.IsValid())
      {
        GECKO_WARN(app::graphics_example::labels::Main,
                   "Swapchain %u not created (NullDevice?)", i);
      }
    }

    // ── Offscreen render target ───────────────────────────────────
    constexpr u32 OffscreenW = 1280;
    constexpr u32 OffscreenH = 720;
    constexpr auto OffscreenFmt = DataFormat::R8G8B8A8_UNORM;

    RenderTargetDesc rtDesc;
    rtDesc.Width = OffscreenW;
    rtDesc.Height = OffscreenH;
    rtDesc.NumRenderTargets = 1;
    rtDesc.RenderTargetFormats[0] = OffscreenFmt;
    rtDesc.RenderTargetClearValues[0] =
        ClearValue::RenderTarget(0.1F, 0.1F, 0.15F, 1.0F);

    RenderTarget offscreenRT = device->CreateRenderTarget(rtDesc);
    if (offscreenRT.IsValid())
      GECKO_INFO(app::graphics_example::labels::Main,
                 "Offscreen render target created (%ux%u)", OffscreenW,
                 OffscreenH);
    else
      GECKO_WARN(app::graphics_example::labels::Main,
                 "Offscreen render target creation failed");

    // ── Storage textures written by the plasma compute shader ────
    // Two separate outputs so two job-system workers can dispatch compute
    // in parallel without aliasing. HLSL's `RWTexture2D<float4>` compiles
    // to SPIR-V with an Rgba32f format operand (glslc's HLSL front-end
    // ignores [[vk::image_format]]) — match that here.
    TextureDesc plasmaDesc {};
    plasmaDesc.Width = OffscreenW;
    plasmaDesc.Height = OffscreenH;
    plasmaDesc.Format = DataFormat::R32G32B32A32_FLOAT;
    plasmaDesc.Type = TextureType::Tex2D;
    plasmaDesc.Memory = MemoryType::Dedicated;
    plasmaDesc.AllowUnorderedAccess = true;

    Texture plasmaTex[2] {};
    for (u32 i = 0; i < 2; ++i)
    {
      plasmaDesc.DebugName =
          (i == 0) ? "PlasmaStorageTexture[0]" : "PlasmaStorageTexture[1]";
      plasmaTex[i] = device->CreateTexture(plasmaDesc);
    }
    if (plasmaTex[0].IsValid() && plasmaTex[1].IsValid())
      GECKO_INFO(app::graphics_example::labels::Main,
                 "Plasma storage textures created (2x %ux%u)", OffscreenW,
                 OffscreenH);
    else
      GECKO_WARN(app::graphics_example::labels::Main,
                 "Plasma storage texture creation failed");

    // ── Vertex buffer for triangle ───────────────────────────────
    VertexBufferDesc vbDesc;
    vbDesc.NumVertices = 3;
    vbDesc.VertexSize = sizeof(Vertex);
    vbDesc.Memory = MemoryType::Dedicated;

    Buffer vertexBuffer = device->CreateVertexBuffer(vbDesc);
    if (vertexBuffer.IsValid())
    {
      const auto* raw = reinterpret_cast<const gecko::byte*>(TriangleVertices);
      const usize size = sizeof(TriangleVertices);
      device->UploadBufferData(vertexBuffer, {raw, size});
    }

    // ── Shader binaries (generated by CMake from HLSL sources) ──
    namespace shaders = ::gecko::graphics_example::shaders;

    // ── Pipeline 1: triangle -> offscreen RT ─────────────────────
    VertexLayout triLayout;
    triLayout.AddAttribute(DataFormat::R32G32B32_FLOAT, "a_Position");
    triLayout.AddAttribute(DataFormat::R32G32B32_FLOAT, "a_Color");

    GraphicsPipelineDesc triPDesc;
    triPDesc.VertexShader = ShaderCode {
        .Format = ShaderFormat::SPIRV,
        .Bytes = {reinterpret_cast<const gecko::byte*>(shaders::TriangleVert),
                  sizeof(shaders::TriangleVert)},
    };
    triPDesc.PixelShader = ShaderCode {
        .Format = ShaderFormat::SPIRV,
        .Bytes = {reinterpret_cast<const gecko::byte*>(shaders::TriangleFrag),
                  sizeof(shaders::TriangleFrag)},
    };
    triPDesc.Layout = triLayout;
    triPDesc.NumRenderTargets = 1;
    triPDesc.RenderTargetFormats[0] = OffscreenFmt;
    triPDesc.Culling = CullMode::None;
    triPDesc.PushConstantBytes = 16;  // float Time + 3 pad
    triPDesc.DebugName = "TrianglePipeline";

    GraphicsPipeline trianglePipeline =
        device->CreateGraphicsPipeline(triPDesc);

    // ── Pipeline 2: fullscreen blit -> swapchain ─────────────────
    // Same pipeline used against both swapchains (their backbuffers use the
    // same format).  Binding 0: SRV sampled image. Binding 1: sampler.
    GraphicsPipelineDesc blitPDesc;
    blitPDesc.VertexShader = ShaderCode {
        .Format = ShaderFormat::SPIRV,
        .Bytes = {reinterpret_cast<const gecko::byte*>(shaders::FullscreenVert),
                  sizeof(shaders::FullscreenVert)},
    };
    blitPDesc.PixelShader = ShaderCode {
        .Format = ShaderFormat::SPIRV,
        .Bytes = {reinterpret_cast<const gecko::byte*>(shaders::FullscreenFrag),
                  sizeof(shaders::FullscreenFrag)},
    };
    blitPDesc.Layout = {};  // no vertex input
    blitPDesc.NumRenderTargets = 1;
    blitPDesc.RenderTargetFormats[0] = slots[0].SC.IsValid()
                                           ? slots[0].SC.Desc.Format
                                           : DataFormat::R8G8B8A8_UNORM;
    blitPDesc.Culling = CullMode::None;

    blitPDesc.PipelineResources[0] =
        PipelineResource::TextureBinding(1, ShaderType::Pixel);
    blitPDesc.PipelineResources[1] =
        PipelineResource::SamplerBinding(1, ShaderType::Pixel);
    blitPDesc.NumPipelineResources = 2;
    blitPDesc.PushConstantBytes = 16;  // float4 Tint
    blitPDesc.DebugName = "BlitPipeline";

    GraphicsPipeline blitPipeline = device->CreateGraphicsPipeline(blitPDesc);

    // ── Pipeline 3: plasma compute -> plasmaTex ──────────────────
    ComputePipelineDesc plasmaPDesc;
    plasmaPDesc.ComputeShader = ShaderCode {
        .Format = ShaderFormat::SPIRV,
        .Bytes = {reinterpret_cast<const gecko::byte*>(shaders::PlasmaComp),
                  sizeof(shaders::PlasmaComp)},
    };
    plasmaPDesc.PipelineResources[0] =
        PipelineResource::RWTextureBinding(1, ShaderType::Compute);
    plasmaPDesc.NumPipelineResources = 1;
    plasmaPDesc.PushConstantBytes = 16;  // float Time + 3 pad
    plasmaPDesc.DebugName = "PlasmaComputePipeline";

    ComputePipeline plasmaPipeline = device->CreateComputePipeline(plasmaPDesc);
    if (plasmaPipeline.IsValid())
      GECKO_INFO(app::graphics_example::labels::Main,
                 "Compute pipeline ready (plasma)");
    else
      GECKO_WARN(app::graphics_example::labels::Main,
                 "Plasma compute pipeline creation failed");

    SamplerDesc blitSamplerDesc {};
    blitSamplerDesc.Filter = SamplerFilter::Linear;
    blitSamplerDesc.WrapMode = SamplerWrapMode::Clamp;
    blitSamplerDesc.DebugName = "BlitSampler";
    Sampler blitSampler = device->CreateSampler(blitSamplerDesc);

    // ── Indirect draw args buffer (VkDrawIndirectCommand layout) ─
    // {vertexCount=3, instanceCount=1, firstVertex=0, firstInstance=0}
    StructuredBufferDesc indirectDesc {};
    indirectDesc.NumElements = 1;
    indirectDesc.ElementSize = 16;  // 4 × u32
    indirectDesc.Memory = MemoryType::Dedicated;
    indirectDesc.DebugName = "TriangleIndirectArgs";
    Buffer indirectBuffer = device->CreateStructuredBuffer(indirectDesc);
    if (indirectBuffer.IsValid())
    {
      const u32 indirectArgs[4] = {3, 1, 0, 0};
      device->UploadBufferData(
          indirectBuffer, {reinterpret_cast<const gecko::byte*>(indirectArgs),
                           sizeof(indirectArgs)});
    }

    // ── Timestamp query pool (4 slots: pass1-begin/end, blit-begin/end) ──
    QueryPoolDesc qpDesc {};
    qpDesc.Count = 4;
    qpDesc.DebugName = "FrameTimestamps";
    QueryPool timestampPool = device->CreateTimestampQueryPool(qpDesc);

    // ── GPU profiler sampler (profiler v2) ───────────────────────────
    // Records GPU timestamps for any zone wrapped with
    // GECKO_GPU_PROF_SCOPE and emits matched ProfEvents into the
    // global IProfiler with ProfSource::GPU.
    GpuSamplerDesc samplerDesc {};
    samplerDesc.MaxZonesPerFrame = 16;
    samplerDesc.FramesInFlight = 3;
    samplerDesc.GpuThreadName = "GPU";
    Unique<IGpuSampler> gpuSampler = device->CreateGpuSampler(samplerDesc);
    if (gpuSampler)
      GECKO_INFO(app::graphics_example::labels::Main,
                 "GPU profiler sampler created");

    if (!trianglePipeline.IsValid() || !blitPipeline.IsValid())
    {
      GECKO_WARN(app::graphics_example::labels::Main,
                 "One or more pipelines failed to build — rendering disabled");
    }
    else
    {
      GECKO_INFO(app::graphics_example::labels::Main,
                 "Pipelines ready (triangle + fullscreen blit)");
    }

    // ── Event subscriptions ───────────────────────────────────────
    bool running = true;

    // Optional: exit cleanly after N frames so automated runs (and
    // headless CI) get a properly terminated trace file. Set
    // GECKO_EXAMPLE_MAX_FRAMES to a positive integer.
    const u64 maxFrames = []() -> u64 {
      const char* v = ::std::getenv("GECKO_EXAMPLE_MAX_FRAMES");
      if (!v || !v[0])
        return 0;
      char* e = nullptr;
      auto n = ::std::strtoull(v, &e, 10);
      return n;
    }();

    auto closeSub = SubscribeEvent(
        events::WindowCloseRequested,
        [](void* user, const EventMeta&, EventView view) {
          (void)view;
          *static_cast<bool*>(user) = false;
        },
        &running);

    struct ResizeContext
    {
      WindowSlot* Slots {nullptr};
    };
    ResizeContext rctx {slots};

    auto resizeSub = SubscribeEvent(
        events::WindowResized,
        [](void* user, const EventMeta&, EventView view) {
          const auto* payload =
              reinterpret_cast<const events::WindowResizedPayload*>(
                  view.Data());
          auto* rc = static_cast<ResizeContext*>(user);
          for (u32 i = 0; i < 2; ++i)
          {
            if (rc->Slots[i].Handle == payload->Window)
            {
              rc->Slots[i].ResizeW = payload->Width;
              rc->Slots[i].ResizeH = payload->Height;
              rc->Slots[i].ResizeDirty = true;
            }
          }
        },
        &rctx);

    auto keySub = SubscribeEvent(
        events::WindowKey,
        [](void* user, const EventMeta&, EventView view) {
          const auto* payload =
              reinterpret_cast<const events::WindowKeyPayload*>(view.Data());
          if (!payload->Down || payload->Repeat)
            return;
          auto* prof = ::gecko::GetProfiler();
          switch (payload->Key)
          {
          case KeyCode::Escape:
            *static_cast<bool*>(user) = false;
            break;
          case KeyCode::F1:
            if (prof)
            {
              bool on = !prof->IsTraceEnabled();
              prof->SetTraceEnabled(on);
              GECKO_INFO(app::graphics_example::labels::Main,
                         "[F1] trace file output: {}", on ? "ON" : "OFF");
            }
            break;
          case KeyCode::F2:
            if (prof)
            {
              ::gecko::ProfLevel cur = prof->GetMinLevel();
              ::gecko::ProfLevel next = (cur == ::gecko::ProfLevel::Always)
                                            ? ::gecko::ProfLevel::Normal
                                        : (cur == ::gecko::ProfLevel::Normal)
                                            ? ::gecko::ProfLevel::Detailed
                                            : ::gecko::ProfLevel::Always;
              prof->SetMinLevel(next);
              const char* names[3] = {"Always", "Normal", "Detailed"};
              GECKO_INFO(app::graphics_example::labels::Main,
                         "[F2] min profiler level: {}",
                         names[static_cast<int>(next)]);
            }
            break;
          case KeyCode::F3:
            // F3 cycles the Detailed sample rate: 1, 8, 64, 0, 1, ...
            if (prof)
            {
              u32 r = prof->GetDetailedSampleRate();
              u32 next = (r == 1) ? 8u : (r == 8) ? 64u : (r == 64) ? 0u : 1u;
              prof->SetDetailedSampleRate(next);
              GECKO_INFO(app::graphics_example::labels::Main,
                         "[F3] Detailed sample rate: 1/{}",
                         next == 0 ? 0 : next);
            }
            break;
          case KeyCode::F4:
            if (prof)
              prof->DumpStats(app::graphics_example::labels::Main);
            break;
          default:
            break;
          }
        },
        &running);

    GECKO_INFO(app::graphics_example::labels::Main,
               "Entering frame loop — Escape or close to quit");

    const auto startTime = ::std::chrono::steady_clock::now();
    u64 frameIndex = 0;

    auto renderFrame = [&]() {
      GECKO_SCOPE_ALWAYS_NAMED(app::graphics_example::labels::Main,
                               "renderFrame");
      // Coalesce pending resizes into a single swapchain rebuild per window.
      for (u32 i = 0; i < 2; ++i)
      {
        if (slots[i].ResizeDirty)
        {
          if (slots[i].ResizeW > 0 && slots[i].ResizeH > 0)
          {
            slots[i].SC.Desc.Width = slots[i].ResizeW;
            slots[i].SC.Desc.Height = slots[i].ResizeH;
          }
          device->ResizeSwapchain(slots[i].SC);
          slots[i].ResizeDirty = false;
        }
      }

      if (!trianglePipeline.IsValid() || !blitPipeline.IsValid() ||
          !vertexBuffer.IsValid() || !offscreenRT.IsValid())
        return;

      // Acquire both swapchains (skip any that fail).
      FrameContext frames[2] {};
      for (u32 i = 0; i < 2; ++i)
      {
        if (slots[i].SC.IsValid())
          frames[i] = device->BeginFrame(slots[i].SC);
      }
      if (!frames[0].Valid && !frames[1].Valid)
        return;

      auto cmd = device->CreateGraphicsCommandList();
      cmd->Begin();

      if (gpuSampler)
      {
        gpuSampler->BeginFrame(*cmd);
        // Auto-wrap every Draw/DrawIndexed/DrawIndirect/Dispatch on this
        // command list in a GPU zone (nested under our manual TrianglePass /
        // BlitPass zones). Detailed level only.
        cmd->AttachGpuSampler(gpuSampler.get(),
                              app::graphics_example::labels::Main);
      }

      const bool haveTimestamps = timestampPool.IsValid();
      if (haveTimestamps)
        cmd->ResetTimestamps(timestampPool, 0, 4);

      const f32 time = ::std::chrono::duration<f32>(
                           ::std::chrono::steady_clock::now() - startTime)
                           .count();

      // ── Parallel compute ─────────────────────────────────────────
      // Record two plasma dispatches on separate job-system workers, each
      // writing into its own storage texture. This exercises the engine's
      // per-thread Vulkan command pools + queue-submit mutex. We only
      // record in parallel; submission itself is serialised on the main
      // thread so the blit pass below can assume both compute textures are
      // already in SHADER_READ_ONLY when it runs.
      const bool haveCompute = plasmaPipeline.IsValid() &&
                               plasmaTex[0].IsValid() && plasmaTex[1].IsValid();

      // Fake "terrain generation" scope, tagged with the 'terrain' category
      // so it can be filtered independently. Spends ~50us doing nothing
      // useful — this is just to demo feature-scoped profiling. Its scope
      // shows up in the trace under the 'terrain' category and contributes
      // to GetStats("FakeTerrainGen").
      {
        ::gecko::ProfScope _terrain {app::graphics_example::labels::Main,
                                     ::gecko::FNV1a("FakeTerrainGen"),
                                     "FakeTerrainGen",
                                     ::gecko::ProfLevel::Detailed, catTerrain};
        volatile u64 acc = 0;
        for (u32 i = 0; i < 5000; ++i)
          acc += i * frameIndex;
        (void)acc;
      }

      Unique<ICommandList> computeCmd[2];

      if (haveCompute)
      {
        GECKO_SCOPE_NAMED(app::graphics_example::labels::Main, "ComputePass");
        // Record both compute command lists on the main render thread
        // (no job-system fan-out) so the profiler trace shows them on
        // the main row instead of scattering across job workers.
        for (u32 i = 0; i < 2; ++i)
        {
          const f32 tOffset = (i == 0) ? 0.0F : 3.14159F;
          computeCmd[i] = device->CreateComputeCommandList();
          if (!computeCmd[i])
            continue;
          computeCmd[i]->Begin();
          computeCmd[i]->BindPipeline(plasmaPipeline);
          computeCmd[i]->BindRWTexture(0, plasmaTex[i]);
          f32 pc[4] = {time + tOffset, 0.0F, 0.0F, 0.0F};
          computeCmd[i]->SetConstants(
              0, {reinterpret_cast<const gecko::byte*>(pc), sizeof(pc)});
          const u32 gx = (OffscreenW + 15) / 16;
          const u32 gy = (OffscreenH + 15) / 16;
          computeCmd[i]->Dispatch(gx, gy, 1);
          computeCmd[i]->TransitionTextureForRead(plasmaTex[i]);
          computeCmd[i]->End();
        }
        // Submit from the main thread, in deterministic order.
        for (u32 i = 0; i < 2; ++i)
          if (computeCmd[i])
            device->ExecuteComputeCommandList(::std::move(computeCmd[i]));
      }

      // Pass 1: render the spinning-coloured triangle into the offscreen RT
      // using an indirect draw + time push constant.
      ClearValue rtClear = ClearValue::RenderTarget(0.08F, 0.08F, 0.12F, 1.0F);
      cmd->BeginRendering(offscreenRT, &rtClear);
      cmd->SetViewport(0.0F, 0.0F, static_cast<f32>(OffscreenW),
                       static_cast<f32>(OffscreenH));
      cmd->SetScissor(0, 0, OffscreenW, OffscreenH);
      cmd->BindPipeline(trianglePipeline);
      cmd->BindVertexBuffer(vertexBuffer);
      {
        f32 pc[4] = {time, 0.0F, 0.0F, 0.0F};
        cmd->SetConstants(
            0, {reinterpret_cast<const gecko::byte*>(pc), sizeof(pc)});
      }
      if (haveTimestamps)
        cmd->WriteTimestamp(timestampPool, 0);
      {
        // GPU-side profiler zone (Normal level so it survives default
        // trace filtering even when Detailed is dropped).
        GECKO_GPU_SCOPE_NORMAL_NAMED(*cmd, app::graphics_example::labels::Main,
                                     "TrianglePass");
        if (indirectBuffer.IsValid())
          cmd->DrawIndirect(indirectBuffer, 0, 1, 16);
        else
          cmd->Draw(3);
      }
      if (haveTimestamps)
        cmd->WriteTimestamp(timestampPool, 1);
      cmd->EndRendering();
      // After EndRendering the offscreen target is in SHADER_READ_ONLY.

      // Pass 2 & 3: fullscreen-quad blit into each swapchain. Window A
      // samples the triangle offscreen RT; Window B samples the plasma
      // compute output. One command list, one submit, one Present.
      const Texture& triSampled = offscreenRT.RenderTextures[0];
      const bool havePlasma = plasmaPipeline.IsValid() &&
                              plasmaTex[0].IsValid() && plasmaTex[1].IsValid();

      // Tint pulses between 0.6 and 1.0 over time so push constants are
      // visibly affecting output.
      const f32 pulse = 0.8F + 0.2F * ::std::sin(time * 2.0F);
      const f32 tintArr[4] = {pulse, pulse, pulse, 1.0F};

      if (haveTimestamps)
        cmd->WriteTimestamp(timestampPool, 2);
      {
        GECKO_GPU_SCOPE_NORMAL_NAMED(*cmd, app::graphics_example::labels::Main,
                                     "BlitPass");
        for (u32 i = 0; i < 2; ++i)
        {
          if (!frames[i].Valid)
            continue;
          const Texture& src = (i == 1 && havePlasma)   ? plasmaTex[1]
                               : (i == 0 && havePlasma) ? plasmaTex[0]
                                                        : triSampled;
          ClearValue scClear = ClearValue::RenderTarget(0.0F, 0.0F, 0.0F, 1.0F);
          cmd->BeginRendering(frames[i].BackBuffer, &scClear);
          cmd->SetViewport(0.0F, 0.0F,
                           static_cast<f32>(frames[i].BackBuffer.Desc.Width),
                           static_cast<f32>(frames[i].BackBuffer.Desc.Height));
          cmd->SetScissor(0, 0, frames[i].BackBuffer.Desc.Width,
                          frames[i].BackBuffer.Desc.Height);
          cmd->BindPipeline(blitPipeline);
          cmd->BindTexture(0, src);
          cmd->BindSampler(1, blitSampler);
          cmd->SetConstants(0, {reinterpret_cast<const gecko::byte*>(tintArr),
                                sizeof(tintArr)});
          cmd->Draw(3);
          cmd->EndRendering();
        }
      }
      if (haveTimestamps)
        cmd->WriteTimestamp(timestampPool, 3);

      if (gpuSampler)
        gpuSampler->EndFrame(*cmd);

      cmd->End();
      device->ExecuteGraphicsCommandList(::std::move(cmd));

      // Present both swapchains in one driver call.
      FrameContext toPresent[2] {};
      u32 presentCount = 0;
      for (u32 i = 0; i < 2; ++i)
      {
        if (frames[i].Valid)
          toPresent[presentCount++] = ::std::move(frames[i]);
      }
      device->Present(
          ::std::span<const FrameContext> {toPresent, presentCount});

      // Counter: 1 indirect tri draw + 1 blit draw per valid swapchain.
      u32 drawCalls = 1u;
      for (u32 i = 0; i < 2; ++i)
        if (frames[i].Valid)
          ++drawCalls;
      GECKO_COUNTER(app::graphics_example::labels::Main, "DrawCalls",
                    drawCalls);
      {
        u64 live = trackingAlloc.TotalLiveBytes();
        GECKO_COUNTER(app::graphics_example::labels::Main, "AllocLiveBytes",
                      live);
      }
      // Log GPU timings once per ~60 frames (WAIT-blocks until ready).
      // Profiler-driven HUD: print frame + per-pass timings every ~1 s.
      // CPU values come from WatchScope("frame")/("renderFrame") and the
      // GPU-side ones from the gpu_profiler events fed into the same
      // aggregator (keyed on ProfSource::GPU). No QueryPool poll needed.
      static u64 s_LastHudPrintNs = 0;
      const u64 nowNs = ::gecko::GetProfiler()->NowNs();
      if (nowNs - s_LastHudPrintNs > 1'000'000'000ULL)
      {
        s_LastHudPrintNs = nowNs;
        auto* prof = ::gecko::GetProfiler();
        auto frame = prof->GetStats("frame");
        auto rend = prof->GetStats("renderFrame");
        auto tri = prof->GetStats("TrianglePass", ::gecko::ProfSource::GPU);
        auto blit = prof->GetStats("BlitPass", ::gecko::ProfSource::GPU);
        f64 fps =
            (frame.AvgNs > 0) ? 1.0e9 / static_cast<f64>(frame.AvgNs) : 0.0;
        u64 live = trackingAlloc.TotalLiveBytes();
        GECKO_INFO(app::graphics_example::labels::Main,
                   "HUD frame=%.2fms (%.1f fps)  cpu_render=%.2fms  "
                   "gpu_tri=%.3fms  gpu_blit=%.3fms  draws=%u  "
                   "alloc_live=%llu KB  frames=%llu",
                   frame.AvgNs / 1.0e6, fps, rend.AvgNs / 1.0e6,
                   tri.AvgNs / 1.0e6, blit.AvgNs / 1.0e6, drawCalls,
                   (unsigned long long)(live / 1024),
                   (unsigned long long)frameIndex);
      }
      ++frameIndex;
    };

    auto update = [&]() {
      GECKO_SCOPE_ALWAYS_NAMED(app::graphics_example::labels::Main, "frame");
      (void)DispatchEvents();
      renderFrame();
      GECKO_FRAME(app::graphics_example::labels::Main, "Frame");
    };

    ::gecko::platform::SetModalFrameCallback(
        [](void* ud) { (*static_cast<decltype(&update)>(ud))(); }, &update);

    while (running)
    {
      if (maxFrames && frameIndex >= maxFrames)
        running = false;
      ::gecko::platform::PumpEvents();
      update();
    }

    ::gecko::platform::SetModalFrameCallback(nullptr, nullptr);

    // Destroy in reverse order.
    for (u32 i = 0; i < 2; ++i)
    {
      device->DestroySwapchain(slots[i].SC);
      ::gecko::platform::GetWindows()->DestroyWindow(slots[i].Handle);
    }

    GECKO_INFO(app::graphics_example::labels::Main, "Shutdown complete");
  }

  consoleSink.Unregister();
  fileSink.Unregister();
  // NOTE: do NOT explicitly Unregister traceSink here. The outer GECKO_SCOPE
  // scope object is destroyed at function exit AFTER this line runs but
  // BEFORE traceSink (since traceSink was declared earlier). Unregistering
  // here would detach the sink before GECKO_SCOPE's ZoneEnd fires, leaving
  // the main scope visibly "[incomplete]" in trace viewers. RAII does the
  // right thing: traceSink dtor unregisters, drains, then closes.

  engine.reset();
  ResetAllocator();
  ::std::printf("Graphics example finished.\n");
  return 0;
}
