#pragma once

#include "gecko/core/api.h"
#include "gecko/core/labels.h"
#include "gecko/core/types.h"
#include "gecko/core/utility/hash.h"

#include <span>

namespace gecko {

class IModuleRegistry;

// Stable, opaque identifier for a service interface type. Generated by
// hashing the type's pretty-name; stable across translation units within
// one build of the same compiler / flags. Two ServiceIds compare equal
// iff they were produced from the same type T.
struct ServiceId
{
  u64 Value {0};

  [[nodiscard]] constexpr bool operator==(const ServiceId& other) const noexcept
  {
    return Value == other.Value;
  }
};

template <class T>
[[nodiscard]] consteval ServiceId ServiceIdOf() noexcept
{
  return ServiceId {FNV1a64(__PRETTY_FUNCTION__)};
}

enum class ModuleResult : u8
{
  Ok = 0,
  InvalidArgument,
  DuplicateModule,
  NotFound,
  StartupFailed,
  OutOfMemory
};

struct IModule
{
  virtual ~IModule() = default;

  [[nodiscard]] GECKO_API virtual Label RootLabel() const noexcept = 0;

  [[nodiscard]] GECKO_API virtual bool Startup(
      IModuleRegistry& modules) noexcept = 0;

  GECKO_API virtual void Shutdown(IModuleRegistry& modules) noexcept = 0;

  // Service IDs that this module publishes during Startup(). The engine
  // uses this together with Requires() to compute startup order. Default
  // empty: the module publishes no services.
  [[nodiscard]] GECKO_API virtual ::std::span<const ServiceId> Publishes()
      const noexcept
  {
    return {};
  }

  // Service IDs that this module needs to be available before its
  // Startup() runs. The engine guarantees Startup() is not called until
  // every Required ServiceId has been Published by some other module
  // earlier in the topo order. Default empty: the module has no service
  // dependencies.
  [[nodiscard]] GECKO_API virtual ::std::span<const ServiceId> Requires()
      const noexcept
  {
    return {};
  }
};

class ModuleHandle
{
public:
  ModuleHandle() = default;
  ModuleHandle(const ModuleHandle&) =
      delete ("ModuleHandle is move-only; each handle has unique ownership");
  ModuleHandle& operator=(const ModuleHandle&) =
      delete ("ModuleHandle is move-only; each handle has unique ownership");

  GECKO_API ModuleHandle(ModuleHandle&& other) noexcept;
  GECKO_API ModuleHandle& operator=(ModuleHandle&& other) noexcept;
  GECKO_API ~ModuleHandle() noexcept;

  [[nodiscard]] GECKO_API Label RootLabel() const noexcept
  {
    return m_label;
  }
  [[nodiscard]] GECKO_API explicit operator bool() const noexcept
  {
    return m_modules != nullptr && m_label.IsValid();
  }

  GECKO_API void Reset() noexcept;

  GECKO_API void Release() noexcept;

private:
  friend class IModuleRegistry;
  GECKO_API ModuleHandle(IModuleRegistry* modules, Label label) noexcept;

  IModuleRegistry* m_modules {nullptr};
  Label m_label {};
};

struct ModuleRegistration
{
  ModuleHandle Handle;
  ModuleResult Result {ModuleResult::InvalidArgument};

  [[nodiscard]] bool Ok() const noexcept
  {
    return Result == ModuleResult::Ok;
  }
};

class IModuleRegistry
{
public:
  virtual ~IModuleRegistry() = default;

  [[nodiscard]] GECKO_API virtual bool Init() noexcept = 0;
  GECKO_API virtual void Shutdown() noexcept = 0;

  [[nodiscard]] GECKO_API virtual ModuleRegistration RegisterStatic(
      IModule& module) noexcept = 0;

  [[nodiscard]] GECKO_API virtual ModuleResult Unregister(
      Label module) noexcept = 0;

  [[nodiscard]] GECKO_API virtual IModule* GetModule(Label module) noexcept = 0;
  [[nodiscard]] GECKO_API virtual const IModule* GetModule(
      Label module) const noexcept = 0;

  using ModuleVisitFn = void (*)(IModule& module, bool started,
                                 void* user) noexcept;
  GECKO_API virtual void ForEachModule(ModuleVisitFn fn,
                                       void* user) noexcept = 0;

  [[nodiscard]] GECKO_API virtual bool StartupAllModules() noexcept = 0;
  GECKO_API virtual void ShutdownAllModules() noexcept = 0;

  // Service registry: modules call PublishService<T> during their
  // Startup() to make their interface impl available. Other modules and
  // the rest of the app retrieve it via Service<T>(). Returns false on
  // duplicate publish or null impl.
  [[nodiscard]] GECKO_API virtual bool PublishServiceImpl(
      ServiceId id, void* impl) noexcept = 0;
  [[nodiscard]] GECKO_API virtual void* GetServiceImpl(
      ServiceId id) const noexcept = 0;
  [[nodiscard]] GECKO_API virtual bool UnpublishServiceImpl(
      ServiceId id) noexcept = 0;

  template <class T>
  [[nodiscard]] bool PublishService(T* impl) noexcept
  {
    return PublishServiceImpl(ServiceIdOf<T>(), impl);
  }

  template <class T>
  [[nodiscard]] T* Service() const noexcept
  {
    return static_cast<T*>(GetServiceImpl(ServiceIdOf<T>()));
  }

  template <class T>
  bool UnpublishService() noexcept
  {
    return UnpublishServiceImpl(ServiceIdOf<T>());
  }

protected:
  [[nodiscard]] ModuleHandle MakeHandle(Label label) noexcept
  {
    return ModuleHandle {this, label};
  }
};

struct NullModuleRegistry final : IModuleRegistry
{
  [[nodiscard]] GECKO_API virtual bool Init() noexcept override;
  GECKO_API virtual void Shutdown() noexcept override;

  [[nodiscard]] GECKO_API virtual ModuleRegistration RegisterStatic(
      IModule& module) noexcept override;
  [[nodiscard]] GECKO_API virtual ModuleResult Unregister(
      Label module) noexcept override;

  [[nodiscard]] GECKO_API virtual IModule* GetModule(
      Label module) noexcept override;
  [[nodiscard]] GECKO_API virtual const IModule* GetModule(
      Label module) const noexcept override;

  GECKO_API virtual void ForEachModule(ModuleVisitFn fn,
                                       void* user) noexcept override;

  [[nodiscard]] GECKO_API virtual bool StartupAllModules() noexcept override;
  GECKO_API virtual void ShutdownAllModules() noexcept override;

  [[nodiscard]] GECKO_API virtual bool PublishServiceImpl(
      ServiceId id, void* impl) noexcept override;
  [[nodiscard]] GECKO_API virtual void* GetServiceImpl(
      ServiceId id) const noexcept override;
  [[nodiscard]] GECKO_API virtual bool UnpublishServiceImpl(
      ServiceId id) noexcept override;
};

}  // namespace gecko
