#pragma once

#ifndef GECKO_VERSION_MAJOR
#define GECKO_VERSION_MAJOR 0
#endif

#ifndef GECKO_VERSION_MINOR
#define GECKO_VERSION_MINOR 0
#endif

#ifndef GECKO_VERSION_PATCH
#define GECKO_VERSION_PATCH 0
#endif

#ifndef GECKO_VERSION_STRING
#define GECKO_VERSION_STRING "0.0.0"
#endif

#ifndef GECKO_VERSION_PRERELEASE
#define GECKO_VERSION_PRERELEASE ""
#endif

#ifndef GECKO_VERSION_FULL_STRING
#define GECKO_VERSION_FULL_STRING GECKO_VERSION_STRING
#endif
