#include <stdio.h>

namespace {

bool FilesEqual(const char* firstPath, const char* secondPath)
{
  ::FILE* first = ::fopen(firstPath, "rb");
  ::FILE* second = ::fopen(secondPath, "rb");
  if (first == nullptr || second == nullptr)
  {
    if (first != nullptr)
      ::fclose(first);
    if (second != nullptr)
      ::fclose(second);
    return false;
  }

  bool equal = true;
  for (;;)
  {
    const int a = ::fgetc(first);
    const int b = ::fgetc(second);
    if (a != b)
    {
      equal = false;
      break;
    }
    if (a == EOF)
      break;
  }

  ::fclose(first);
  ::fclose(second);
  return equal;
}

bool WriteBlob(::FILE* output, const char* inputPath, const char* name)
{
  ::FILE* input = ::fopen(inputPath, "rb");
  if (input == nullptr)
  {
    ::fprintf(stderr, "embed: could not read %s\n", inputPath);
    return false;
  }

  ::fprintf(output, "alignas(4) inline constexpr unsigned char %s[] = {\n", name);
  unsigned column = 0;
  for (;;)
  {
    const int value = ::fgetc(input);
    if (value == EOF)
      break;
    if (column == 0)
      ::fputs("  ", output);
    ::fprintf(output, "0x%02X,", static_cast<unsigned>(value));
    ++column;
    if (column == 16)
    {
      ::fputc('\n', output);
      column = 0;
    }
    else
    {
      ::fputc(' ', output);
    }
  }
  if (column != 0)
    ::fputc('\n', output);
  ::fputs("};\n\n", output);
  ::fclose(input);
  return true;
}

}  // namespace

int main(int argumentCount, char** arguments)
{
  if (argumentCount < 5 || ((argumentCount - 3) % 2) != 0)
  {
    ::fputs("usage: gecko_embed <output-header> <namespace> <input> <name> [<input> <name> ...]\n", stderr);
    return 2;
  }

  const char* outputPath = arguments[1];
  const char* namespaceName = arguments[2];
  char temporaryPath[4096];
  if (::snprintf(temporaryPath, sizeof(temporaryPath), "%s.tmp", outputPath) < 0)
    return 1;

  ::FILE* output = ::fopen(temporaryPath, "wb");
  if (output == nullptr)
  {
    ::fprintf(stderr, "embed: could not write %s\n", temporaryPath);
    return 1;
  }

  ::fputs("// Generated by tools/embed.cpp. Do not edit.\n#pragma once\n\n", output);
  ::fprintf(output, "namespace %s {\n\n", namespaceName);
  bool success = true;
  for (int index = 3; index < argumentCount; index += 2)
    success = WriteBlob(output, arguments[index], arguments[index + 1]) && success;
  ::fprintf(output, "}  // namespace %s\n", namespaceName);
  ::fclose(output);

  if (!success)
  {
    ::remove(temporaryPath);
    return 1;
  }
  if (FilesEqual(temporaryPath, outputPath))
  {
    ::remove(temporaryPath);
    return 0;
  }

  ::remove(outputPath);
  if (::rename(temporaryPath, outputPath) != 0)
  {
    ::fprintf(stderr, "embed: could not replace %s\n", outputPath);
    ::remove(temporaryPath);
    return 1;
  }
  return 0;
}
